### ISSUE TITLE
in ./node_modules/angular-shepherd/fesm5/angular-shepherd.js 297:57-75 [ng] "export 'ɵɵdefineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by Manvender-TC** [shipshapecode/angular-shepherd#10]
```

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.1

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.19
   @capacitor/core           : 1.0.0-beta.19

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 24 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/../Android/Sdk)
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.18

> 
```

**Comment by rwwagner90** [comment]
@Manvender-TC I don't use Angular myself. I don't know what the issue would be here. It works for the example app in the repo.

**Comment by MaSydJun** [comment]
@rwwagner90 I don't think the example (https://github.com/shipshapecode/angular-shepherd/tree/master/projects/shepherd-tester) is comparable to a real live case.

That's most likely because you are importing the service class with this line:
`import { ShepherdService } from '../../../../shepherd/src/lib/shepherd.service';`
What you are importing there is not the compiled (javascript) version of your service-class, but it's the raw typescript class.

When installing the `angular-shepherd` package via a package-manager however, and importing it with:
`import { ShepherdService } from 'angular-shepherd';`
it produces the error mentioned by @Manvender-TC .

**Comment by rwwagner90** [comment]
How do other Angular libraries handle this? It seems odd that it's not possible to release a plugin that supports multiple Angular versions.

**Comment by MaSydJun** [comment]
Honestly my angular knowledge is not sufficient. However, I think it's normal, users are forced to update their angular to the version used to build the library/package with.

**Comment by rwwagner90** [comment]
I do Ember day to day and you can write Ember addons compatible with all versions of Ember. I wish there was a way to opt into this in Angular.

**Comment by Manvender-TC** [comment]
I had fixed the issue by updating existing library in my project . And its perfectly working with ionic project too.

**Comment by BNRao** [comment]
Is there any way that ɵɵdefineInjectable can be replaced with defineInjectable?  I am working on Angular 7 and when I do npm install it is coming with ɵɵdefineInjectable which is not supported by angular 7. May i know any reason why ɵɵdefineInjectable is used?  It would be great if you can change or replace ɵɵdefineInjectable with defineInjectable in the npm package or suggest a way for me to fix this!



Workaround : I was able to resolve the issue if i replace ɵɵdefineInjectable with defineInjectable locally,  but whenever we do npm install  it automatically changes to ɵɵdefineInjectable where I have to update it manually .

Thanks in Advance!

**Comment by rwwagner90** [comment]
@BNRao I am not using anything like that directly. It's just Angular 7 vs Angular 8 compilation differences. I wish Angular had a way to compile for different versions because if it did, this could support a bunch of Angular versions.

**Comment by MaSydJun** [comment]
@BNRao As I already mentioned:

> I guess the main problem is that @tomvangreen and I use angular version 7.2 where as you are using version 8.1. (ɵ signs are used in ivy mode since angular 8.X, afaik).
> 
> Either we (@tomvangreen and I) have to update to angular version 8.1 or we need to downgrade our angular-shepherd version to 0.0.5.

**Comment by janakaedirisinghe** [comment]
I fixed this issue using delete some codes in module package with angular 8 :p
