### ISSUE TITLE
StepOptionsButton 'type' property missing in types #1858

### ISSUE THREAD

**Issue by sebrojas14** [shipshapecode/angular-shepherd#1074]
Look in sheperd repository https://github.com/shipshapecode/shepherd/issues/1858

**Comment by sebrojas14** [comment]
The problem really was that there is not 'type' property any more in the shepherd library. Instead, we should use action like this:
```
buttons: [
      {
        classes: 'shepherd-button-secondary',
        text: 'Exit',
        action: this.shepherdService.cancel
      },
      {
        classes: 'shepherd-button-primary',
        text: 'Back',
        action: this.shepherdService.back
      },
      {
        classes: 'shepherd-button-primary',
        text: 'Next',
        action: this.shepherdService.next
      }
    ],
```

Going to make a PR.

**Comment by rwwagner90** [comment]
@sebrojas14 `type` is definitely a thing. It's part of this wrapper, not part of Shepherd itself. See here https://github.com/shipshapecode/angular-shepherd/blob/master/projects/shepherd/src/lib/utils/buttons.ts#L11

**Comment by sebrojas14** [comment]
[rwwagner90](https://github.com/rwwagner90) so it's bad implemented. If you see, in ShepherdService it's referenced the shepherd.js type that doesn's have type property. https://github.com/shipshapecode/angular-shepherd/blob/master/projects/shepherd/src/lib/shepherd.service.ts#L5
