### ISSUE TITLE
Trouble styling and sizing pop-ups, specifically with images

### ISSUE THREAD

**Issue by harleybl** [shipshapecode/angular-shepherd#12]
Question: I am evaluating whether we can use Shepherd with our application. 
For each step in the tour there is an image that we would like to display.
However whenever I do this the pop-up does not grow to encapsulate the image.
I have tried using a custom class to set the min-width but that doesn't seem to be working. 
How do I specify the width and height of the pop-up? 
Is this something that I need to do in tippy options?

**Comment by harleybl** [comment]
I did have some success styling when I used the tippyOptions to append the dialog to a specific element within my component, however when I do that and use modal = true, the help dialog is completely covered by the semi-transparent overlay.

**Comment by harleybl** [comment]
Actually after some experimentation I was able to figure this out. - Thanks

**Comment by rwwagner90** [comment]
@harleybl we should maybe explain this more in the docs. I think you have to set the width via tippy or it is capped at 400px.
