### ISSUE TITLE
Unable to resolve dependency tree after upgrade project to Angular 14

### ISSUE THREAD

**Issue by symonfly82** [shipshapecode/angular-shepherd#1230]
**Describe the bug**
After upgrading angular project to v14 and running npm install I encountered the error in image below

**To Reproduce**
1. Upgrade an Angular project to v14
2. Run npm install

**Expected behavior**
Dependencies must be upgraded

**Screenshots**
![image](https://user-images.githubusercontent.com/51240626/173525345-a7bc64d9-8112-4a07-87be-fac0b68fd0df.png)

**Comment by rwwagner90** [comment]
v14 was just released
