### ISSUE TITLE
Multilingual application - dynamic text

### ISSUE THREAD

**Issue by amic81** [shipshapecode/angular-shepherd#1302]
Hi,
I wanted to ask if it is possible and if so how to manage the fact of having a multilingual tour.

For example, how can you manage to make the text in dynamic : 

`buttons: [
    {
      text: ???,
      action: tour.next
    }
  ]`
  
  and also title and text in every single step?
  
  Thank you

**Comment by rwwagner90** [comment]
@amic81 you'll have to use some sort of `i18n` package then use that to set your text accordingly.
