### ISSUE TITLE
Does shepherd-theme-arrows work with angular-shepherd?

### ISSUE THREAD

**Issue by Buttars** [shipshapecode/angular-shepherd#15]
I am attempting to use shepherd-theme-arrows from the cloudflare cdn. It causes the model to look like this with the content missing but the arrow showing.
![](https://i.imgur.com/g1zzBVr.png)

Is there something I am missing? Is the angular version compatible with the arrows theme?

**Comment by Buttars** [comment]
I am using angular-shepherd. I wanted to use the arrows theme but it sounds like that is a legacy feature. I think that answers my question, thank you :).

**Comment by rwwagner90** [comment]
@Buttars the arrows theme is built in. It is the default and all styles are shipped with the JS now. If you use angular-shepherd, you get the styles automatically.
