### ISSUE TITLE
Angular v15 support

### ISSUE THREAD

**Issue by dschweinbenz** [shipshapecode/angular-shepherd#1568]
Hey,

it would be great if you could build a new version to be able to use this great library using Angular 15

**Comment by ghbob** [comment]
@rwwagner90 Hi! Any plans yet for Angular 15 support?
I tried it locally and after resetting some Angular 15 dependencies to 14 in the main project dir (dependabot is a bit too eager apparently) `ng update @angular/cli @angular/core` runs without a problem.
After updating to shepherd.js 11 and Angular 15 in the `/projects/shepherd/package.json` the tests are still successful and it seems to work (as far as I can tell).

Thank you!

**Comment by rwwagner90** [comment]
@ghbob would you like to open a PR updating things? It sounds like you have most of it done already.

**Comment by ghbob** [comment]
@rwwagner90 Alright, I tried my best: https://github.com/shipshapecode/angular-shepherd/pull/1584
My experience concerning node package dependencies is limited though, maybe I missed something important :)

**Comment by rwwagner90** [comment]
15.0.0 has been published
