### ISSUE TITLE
Custom action on button not working

### ISSUE THREAD

**Issue by raframil** [shipshapecode/angular-shepherd#158]
So I just get started using Shepherd on my Angular 8 project, unfortunately, I can't do any custom actions inside my buttons.

```
builtInButtons = {
    complete: {
      classes: "finish-button",
      secondary: false,
      text: "Ok",
      type: "cancel",
      action() {
        console.log('finishing my tour')
      },
    },
    next: {
      classes: "next-button",
      text: "Next",
      type: "next"
    },
    back: {
      classes: "back-button",
      secondary: true,
      text: "Back",
      type: "back"
    }
  };

```

console.log() doesn't happen, and I can't see why. Basically what I'm seeking is a way to router.navigate when the user finishes the current tour by clicking or advancing via keyboard.

**Comment by raframil** [comment]
Ok, apparently you can't have a type and an action on the same button. Removing the type "cancel" solved it. I don't know if this is intended, maybe we need this in the docs.

**Comment by rwwagner90** [comment]
Yes, it does seem we do not document the button types well. Would you be interested in opening a PR?

**Comment by raframil** [comment]
Sure!

**Comment by TheVishalK** [comment]
This is really a cool and simple library. However this issue persists. There appears to be no way to route to another component using buttons.

**Comment by rwwagner90** [comment]
@TheVishalK this issue was not an issue, just a documentation mismatch. What's the problem you are experiencing?

**Comment by TheVishalK** [comment]
> @TheVishalK this issue was not an issue, just a documentation mismatch. What's the problem you are experiencing?

I am finding no way to call a custom action. I understand when you quote - you can't have a type and an action on the same button. 

Can you please show an example how can I write a custom action like navigating to another route from a button.

How can I call something like 
this.router.navigateByUrl(['/profile']);

inside the button action.

**Comment by rwwagner90** [comment]
@TheVishalK you can define it in buttons, the same way vanilla Shepherd does.

```js
    buttons: [
      {
        classes: 'shepherd-button-secondary',
        text: 'My action',
        action() { //do some stuff }
      }
   ]
```

**Comment by TheVishalK** [comment]
Yes. The syntax you put is clear in the document. But can you please give an example of a custom event using the angular plugin.

I tried the following.

this.router.navigateByUrl(['/profile']);
 OR
 
   this.zone.runOutsideAngular(() => {
              this.router.navigateByUrl(['/profile']);
          });
		  
But none works. In Angular port for Android, this completely hangs.

Can you give an example please on how to use Angular Plugin with a simple custom action?

**Comment by rwwagner90** [comment]
@TheVishalK my example above is what you want:

```js
buttons: [
  {
    classes: 'shepherd-button-secondary',
    text: 'My action',
    action() {
      this.router.navigateByUrl(['/profile'])
    }
  }
]
```

This is assuming `this.router` is defined here. I'm not an Angular developer, so I don't know where `this.router` comes from. If it's a service it probably has to be injected somehow.

**Comment by yc-98** [comment]
Hii @rwwagner90 ,
I tried using exactly the same way. But doesn't work that way.
message in browser console-
ERROR TypeError: Cannot read properties of undefined ( reading 'navigateByUrl')
console.log works but this doesn't which make me think if while executing shepherd service is not able to refer to navigateByUrl ( I did import this in the component where i use the tour but still the problem persists).
@TheVishalK did you get a solution for this problem?

> @TheVishalK my example above is what you want:
> 
> ```js
> buttons: [
>   {
>     classes: 'shepherd-button-secondary',
>     text: 'My action',
>     action() {
>       this.router.navigateByUrl(['/profile'])
>     }
>   }
> ]
> ```
> 
> This is assuming `this.router` is defined here. I'm not an Angular developer, so I don't know where `this.router` comes from. If it's a service it probably has to be injected somehow.

**Comment by rwwagner90** [comment]
@yc-98 it's a scoping issue. `this` inside the action points to the tour.

Try this:

```js
buttons: [
  {
    classes: 'shepherd-button-secondary',
    text: 'My action',
    action: () => {
      this.router.navigateByUrl(['/profile'])
    }
  }
]
```

As a last resort, you could define a variable for the router.

```js

const router = this.router;

// Setup shepherd stuff here

 action() {
      router.navigateByUrl(['/profile'])
 }
```

Does this make sense?

**Comment by MatZil** [comment]
> @yc-98 it's a scoping issue. `this` inside the action points to the tour.
> 
> Try this:
> 
> ```js
> buttons: [
>   {
>     classes: 'shepherd-button-secondary',
>     text: 'My action',
>     action: () => {
>       this.router.navigateByUrl(['/profile'])
>     }
>   }
> ]
> ```

You are absolutely right, worked like a charm - got a headache from figuring out a way to access service-scoped variables inside the button action - and this is exactly how you do it. Thank you!

**Comment by KusumaKBBHN** [comment]
I am still unable to get the custom function work on button action. 

showTour(pageSteps) {
    this.shepherdService.addSteps(pageSteps);
    const tourId = localStorage.getItem('tour-id');
    const tourFrom = localStorage.getItem('backtoprevious');
    if (tourId && tourFrom == 'true') {
      this.shepherdService.show(tourId);
    } else if (tourId == '10') {
      this.shepherdService.show(tourId);
    } else {
      this.shepherdService.start();
    }
    this.shepherdService.tourObject.on("cancel", this.onTourEnd);
    this.shepherdService.tourObject.on("complete", this.onTourComplete);
  }

  onTourEnd() {
    console.log('TourSkippedByUser');
    localStorage.removeItem('tour-id');
    localStorage.removeItem('backtoprevious');
  }

  onTourComplete() {
    this.UpdateTourTaskStatus();
    console.log('TourCompletedByUser');
    localStorage.removeItem('tour-id');
    localStorage.removeItem('backtoprevious');
  }

  UpdateTourTaskStatus() {
    var updateTour: string = TaskTypes[TaskTypes.takeTour];
    this.updateTaskStatusRequest = {
      taskTypeId: TaskTypes[updateTour],
      actionType: null,
      action: null,
      endOfTask: true
    }
    **_this.coreService_**.updateUserTasks(this.updateTaskStatusRequest, this.loginData).subscribe((result) => {
      if (result.isSuccess) {
        console.log('TourCompletedByUser');
        localStorage.removeItem('tour-id');
        localStorage.removeItem('backtoprevious');
      }
    }, (err) => {
      console.log(err);
    });
  }

**Comment by MatZil** [comment]
> I am still unable to get the custom function work on button action. The value of - this.coreService - is always undefined. I need to find a way to either pass that value or get that value since I need to update the database of the user action showTour(pageSteps) { this.shepherdService.addSteps(pageSteps); this.shepherdService.tourObject.on("cancel", this.onTourEnd); this.shepherdService.tourObject.on("complete", this.onTourComplete); }
> 
> onTourEnd() { console.log('TourSkippedByUser'); }
> 
> onTourComplete() { this.UpdateTourTaskStatus(); console.log('TourCompletedByUser'); }
> 
> UpdateTourTaskStatus() { var updateTour: string = TaskTypes[TaskTypes.takeTour]; this.updateTaskStatusRequest = { taskTypeId: TaskTypes[updateTour], actionType: null, action: null, endOfTask: true } **_this.coreService_**.updateUserTasks(this.updateTaskStatusRequest, this.loginData).subscribe((result) => { if (result.isSuccess) { console.log('TourCompletedByUser'); localStorage.removeItem('tour-id'); localStorage.removeItem('backtoprevious'); } }, (err) => { console.log(err); }); }

Replace

`this.shepherdService.tourObject.on("complete", this.onTourComplete);`

with

`this.shepherdService.tourObject.on("complete", **() =>** this.onTourComplete**()**);`

**Comment by KusumaKBBHN** [comment]
@MatZil Thanks a lot. Worked like a charm.
