### ISSUE TITLE
Wrong position of the dialog in some cases

### ISSUE THREAD

**Issue by lippomano** [shipshapecode/angular-shepherd#163]
In some case I see the dialog out of the screen, especially with a fixed button, for example this step:

`{
                id: 'contacts-new',
                attachTo: {
                    element: '#newContact',
                    on: 'top'
                },
                buttons: [closeButton, backButton, nextButton],
                highlightClass: 'highlight',
                scrollTo: false,
                text: ['text.......'],
            }`

show the dialog not correctly positioned:
![p2](https://user-images.githubusercontent.com/27501745/75334676-8f3a9880-5888-11ea-9e7a-7766719f2cb5.PNG)

this is the button behind the dialog, and I want to display the dialog on top of it, it is a Angular [material button](https://material.angular.io/components/button/overview) with position fixed:
![p1](https://user-images.githubusercontent.com/27501745/75334741-abd6d080-5888-11ea-816a-ccf084942b53.PNG)

P.S. It happens also with the element in the left sidebar.

**Comment by rwwagner90** [comment]
@lippomano can you please try 0.5.0 that I just published? We switched from tether back to popper, so I think that might help.

**Comment by lippomano** [comment]
Oh yes, it seems working.

now I have this error in console:

> ERROR in ../node_modules/angular-shepherd/lib/shepherd.service.d.ts:64:21 - error TS2694: Namespace '"C:/Users/Utente/Desktop/Workspace/optix/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
64     static ɵfac: i0.ɵɵFactoryDef<ShepherdService>;

**Comment by rwwagner90** [comment]
@lippomano sounds like an angular version issue. Unfortunately, angular doesn't offer any easy way to support multiple versions.

**Comment by lippomano** [comment]
ok, I have angular 8.2 at the moment, so I can't use your product now because of angular?...

**Comment by rwwagner90** [comment]
@lippomano yeah,  I updated to Angular 9. I'm not sure how to support both, but if someone knows, I would love to support both.

**Comment by lippomano** [comment]
I can confirm that it works better from the latest update with angular 9
