### ISSUE TITLE
issues integrating with Ionic 4

### ISSUE THREAD

**Issue by jonathan-chin** [shipshapecode/angular-shepherd#174]
Hi,

I've been looking for the perfect tutorial module for my Ionic app. I wrote a quick test project but ran into 2 major issues:

1) when I scroll, the Shepherd popup does not keep attached to its element. it stays in the same position on the screen (ie won't scroll up as the element scrolls up).

2) when the parent element is off screen, the Shepherd popup has its opacity set to 0. I think the intended behavior is for it to turn to 1 when the element scrolls back onto the screen. However, this does not happen in ionic. 

I think the issue is that Ionic renders its content inside fo a shadow dom element.

If there's even the slightest possibility of this being fixed, I'm happy to help contribute to its solution, since it would GREATLY add value to my app.

**Comment by rwwagner90** [comment]
@jonathan-chin if you are experiencing issues, we would certainly love your help fixing them. Sounds like issues with Shepherd in general and not angular-shepherd.

**Comment by rwwagner90** [comment]
Closing this due to no response.
