### ISSUE TITLE
Is it possible to add exitOnEsc property?

### ISSUE THREAD

**Issue by brunorcx** [shipshapecode/angular-shepherd#1742]
Having the exitOnEsc enabled by default its causing some issues here. Could you guys add this one like its on the documentation? 

[exitOnEsc: Exiting the tour with the escape key will be enabled unless this is explicitly set to false.](https://shepherdjs.dev/docs/tutorial-02-usage.html)

I'm not sure if its just a case of adding this property to class 

```
export class ShepherdService {
  confirmCancel = false;
  confirmCancelMessage: string = null;
  defaultStepOptions: Step.StepOptions = {};
  errorTitle = null;
  isActive = false;
  keyboardNavigation = true;
  messageForUser: string = null;
  modal = false;
  requiredElements = [];
  tourName = undefined;
  tourObject: Shepherd.Tour = null;
  **exitOnEsc = true;**
  ....
```
And 

```
const tourObject = new Shepherd.Tour({
      confirmCancel: this.confirmCancel,
      confirmCancelMessage: this.confirmCancelMessage,
      defaultStepOptions: this.defaultStepOptions,
      keyboardNavigation: this.keyboardNavigation,
      tourName: this.tourName,
      useModalOverlay: this.modal,
      **exitOnEsc: this.exitOnEsc**
    });
```

If it is, can I create a pull request for those suggestions?

Thank you in advance!

**Comment by RobbieTheWagner** [comment]
@brunorcx I think doing what you describe should work. Please feel free to open a PR!

**Comment by RobbieTheWagner** [comment]
This has now been added
