### ISSUE TITLE
Add User Interactions

### ISSUE THREAD

**Issue by bharghava52** [shipshapecode/angular-shepherd#190]
The Library looks very useful for better usage and user interactions.
 Can this library allow user interactions with the modules that are highlighted 
and continue the tour based on the user actions performed.

**Comment by rwwagner90** [comment]
@bharghava52 yes, you can definitely do that. You can either manually advance the tour based on whatever actions or you can try using `advanceOn`. Please check out the official Shepherd docs. https://shepherdjs.dev/docs/
