### ISSUE TITLE
Angular-shepherd 14 to 15 breaking

### ISSUE THREAD

**Issue by bashbers** [shipshapecode/angular-shepherd#1965]
Hi there,

We're trying to upgrade one of our applications to Angular-shepherd 15. We've noticed that the popper options that were previously used in shepherd should now be converted to floatingUIOptions:

```ts
    floatingUIOptions: {
        middleware: [{ mainAxis: 0, crossAxis: 36 }]
    },
    // popperOptions: {
    //     modifiers: [{ name: 'offset', options: { offset: [0, 36] } }]
    // **},**

```
As you can see in the snippet above, we've converted it from popperOptions to floatingUIOptions. Except using the angular-shepherd 15 version, we get the following stacktrace inside our console:

<img width="1791" alt="image" src="https://github.com/shipshapecode/angular-shepherd/assets/23037527/54774f80-2d07-434b-b601-970f7b97ac64">

```txt
error_handler.ts:45 ERROR Error: Uncaught (in promise): TypeError: c is not a function
TypeError: c is not a function
    at floating-ui.core.esm.js:126:15
    at Generator.next (<anonymous>)
    at R (asyncToGenerator.js:3:1)
    at z (asyncToGenerator.js:22:1)
    at I.invoke (zone.js:412:30)
    at Object.onInvoke (ng_zone.ts:423:29)
    at I.invoke (zone.js:411:56)
    at I.run (zone.js:169:47)
    at zone.js:1329:38
    at I.invokeTask (zone.js:446:35)
    at Ne (zone.js:1265:35)
    at Ne (zone.js:1219:21)
    at zone.js:1332:21
    at I.invokeTask (zone.js:446:35)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at I.invokeTask (zone.js:445:64)
    at I.runTask (zone.js:214:51)
    at me (zone.js:635:39)
```

We can't figure out why it's behaving like this after the update. The previous update worked fine, but as of right now we're stuck using the Angular 14 version.

Thanks in advance,

Brian

**Comment by RobbieTheWagner** [comment]
@bashbers I think you are missing the `offset` util from floating UI. You need to import it and use it. https://floating-ui.com/docs/offset

**Comment by bashbers** [comment]
That worked, thanks for the fast response!
