### ISSUE TITLE
Shepherd Step Title Issues

### ISSUE THREAD

**Issue by Ryllau** [shipshapecode/angular-shepherd#201]
If the Shepherd Title is too large the text will not wrap nor will the dialog box resize. The Text just rolls off the the side of the dialog box. Is there any fix for this?

**Comment by rwwagner90** [comment]
Can you show an example? You can style it with CSS and make it wrap.

**Comment by rwwagner90** [comment]
Closing due to lack of response. If you are still having issues, let us know!
