### ISSUE TITLE
How to create multi-page tour in an Angular SPA application ?

### ISSUE THREAD

**Issue by NivRash1251** [shipshapecode/angular-shepherd#2041]
I am using Angular 15 and I want the tour to navigate to different pages and show the highlighted section. How to achieve it?

**Comment by XcrashX153** [comment]
so I used a kind of brute force approach for this and I'm sure there are better ways to achieve this, window.location.href = *insert your url here*

**Comment by themadprofessor** [comment]
Add an `action` to the button which sends the user to the other page. In the action, either set a flag somewhere (`sessionStorage` or in a service), or use a query param when navigating. Then use Angular's router to navigate to the other page. In the other page, check for the flag/query param, starting the tour on that page if set. The other page would need its own tour in this case.

**Comment by RobbieTheWagner** [comment]
> Add an `action` to the button which sends the user to the other page. In the action, either set a flag somewhere (`sessionStorage` or in a service), or use a query param when navigating. Then use Angular's router to navigate to the other page. In the other page, check for the flag/query param, starting the tour on that page if set. The other page would need its own tour in this case.

This seems reasonable. You can have one global tour service and start and stop it or create new tours for each page you visit.
