### ISSUE TITLE
Angular 17 Update

### ISSUE THREAD

**Issue by BenTaylorPublic** [shipshapecode/angular-shepherd#2110]
Hi there,
Angular 17 released a few days back, so could this project please be updated with it's new dependencies?
Blog about the release here: https://blog.angular.io/introducing-angular-v17-4d7033312e4b
Also, thanks for the awesome package!

**Comment by ValeryYuntsevichUltralab** [comment]
Dear all,
This update is very welcomed by my team as well. We are looking forward to it too.

**Comment by muhamedkarajic** [comment]
My team as well.

**Comment by Greeny1992** [comment]
We are also looking forward to this update

**Comment by grantfeldman** [comment]
+1

**Comment by VikashRepo123** [comment]
We are looking forward to this update.
