### ISSUE TITLE
publish package (v17.x)

### ISSUE THREAD

**Issue by CodeMaverickVikash** [shipshapecode/angular-shepherd#2115]
Please publish the new version to the npm registry to support angular 17

**Comment by Greeny1992** [comment]
My team is look forward for this update

**Comment by phhbr** [comment]
@RobbieTheWagner may you publish the package, when you have some minutes to spare?

**Comment by rajpeddalachugari** [comment]
@RobbieTheWagner could you please look into this.

**Comment by skhandakar** [comment]
My team are also in desperate need for this

**Comment by RobbieTheWagner** [comment]
17.0.0 published, sorry for the delay!
