### ISSUE TITLE
ERROR in node_modules/angular-shepherd/lib/shepherd.service.d.ts:64:21 - error TS2694: Namespace '"/controlpresencial/ControlPresencialEmpleados/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.

### ISSUE THREAD

**Issue by jotae1e** [shipshapecode/angular-shepherd#212]
I get the error of the title:

`ERROR in node_modules/angular-shepherd/lib/shepherd.service.d.ts:64:21 - error TS2694: Namespace '"/controlpresencial/ControlPresencialEmpleados/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.`

I tried with Ionic4 and Ionic 5 (both with Angular 8).

Can you take a look to this link?  

https://github.com/angular/angular/issues/35291#issuecomment-585092417

Thanks

**Comment by rwwagner90** [comment]
@jotae1e Angular does a very bad job of supporting multiple versions. We are on Angular 9 now, so as far as I know, there is no way to support Angular 8. Would love for an Angular dev to help us support multiple versions, if that is a thing.

**Comment by rwwagner90** [comment]
I just took a look at the disable ivy thing. I am not sure what that is, but we can try it!

**Comment by jotae1e** [comment]
Nice.  I think that may be a solution.

**Comment by rwwagner90** [comment]
@jotae1e I just published 0.6.0. Can you see if it helps? I think it may still require Angular 9.

**Comment by jotae1e** [comment]
Version 0.6 works well with Ionic 5 and Angular 8.  Thanks a lot for your work.

I can not upgrade to Angular 9 because my project has some libraries that not support it (for now).
