### ISSUE TITLE
EMPTY this.shepherdService.steps 

### ISSUE THREAD

**Issue by jotae1e** [shipshapecode/angular-shepherd#213]
I want to remove all the steps of a tour.  

May be with this command:

`this.shepherdService.steps = []`

but it not works.

I've noticed that the steps property is empty.  See this example:
```

   this.shepherdService.modal = true;
   this.shepherdService.confirmCancel = false;

    this.shepherdService.addSteps([
      {
        id: 'ayuda',
        arrow: true,
        attachTo: {
          element: '.step100',
          on: 'bottom'
        },
        buttons: [
          {
            classes: 'boton-salir',
            text: 'Salir',
            type: 'cancel'
          },
          {
            text: 'Atrás',
            type: 'back'
          },
          {
            text: 'Siguiente',
            type: 'next'
          }
        ],
        cancelIcon: {
          enabled: true
        },
        canClickTarget: false,
        scrollTo: false,
        title: 'TITULO',
        text: ['Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500.'],
        modalOverlayOpeningPadding: 5,
        modalOverlayOpeningRadius: 3,
      }

    ]);

    console.log(this.shepherdService.steps);

    this.shepherdService.start();

```
The console.log(this.shepherdService.steps) throws an empty array.

**Comment by rwwagner90** [comment]
The shepherdService would not have steps, I don't think. You would need to set the steps on the actual tour. Perhaps try `this.shepherdService.tourObject.steps = []`. You may have to use the Shepherd `addStep` and `removeStep` APIs.

**Comment by jotae1e** [comment]
Sorry, but I don't understand for what is the property "steps" of the service then?  

I tried to use: 
`this.shepherdService.tourObject.steps = []`

but "steps" doesn't exist in tourObject.

Excuse my insistence but the shepherdjs library has a option property called steps.  In his documentation saids:

steps | Array.<object> \| Array.<Step> | An array of step options objects or Step instances to initialize the tour with
-- | -- | --

Is this property exposed anywhere in angular-shepherd?

Thanks

**Comment by jotae1e** [comment]
And, correct me if I am wrong, but in angular-shepherd, I can only create one tour.  I am working in an ionic app and I want a "tour" for each screen that I have.  With this library I only have a service with one "tour".  For this is important delete all the steps.  Anyway I can do it with "removestep", but is not clean for me.

**Comment by rwwagner90** [comment]
@jotae1e you will want to use just one tour. Setup all your steps for the multiple tours, but just use the one tour service. `steps` should exist on the `tourObject`, as `tourObject` should be the tour. Please experiment with it a bit and look at the Shepherd docs.

Also, the `addSteps` method in the angular service seems to create a new tour each time you call `addSteps`, so I think that should be sufficient? https://github.com/shipshapecode/angular-shepherd/blob/master/projects/shepherd/src/lib/shepherd.service.ts#L89

**Comment by jotae1e** [comment]
It doesn't work. 

I write this service in a project:

```
import { Injectable } from '@angular/core';
import { ShepherdService } from 'angular-shepherd';

@Injectable()


export class TourService {

    public readonly buttons = [
        {
            classes: 'boton-salir',
            text: 'Salir',
            type: 'cancel'
        },
        {
            text: 'Atrás',
            type: 'back'
        },
        {
            text: 'Siguiente',
            type: 'next'
        }
    ];

    constructor(
        private shepherdService: ShepherdService,
    ) {
        this.shepherdService.modal = true;
        this.shepherdService.confirmCancel = false;
        this.shepherdService.defaultStepOptions = {
            arrow: true,
            cancelIcon: {
                enabled: true
            },
            canClickTarget: false,
            modalOverlayOpeningPadding: 5,
            modalOverlayOpeningRadius: 3,
            scrollTo: false,
            popperOptions: {
                modifiers: [
                    {
                      name: 'offset',
                      options: {
                        offset: [0, 15],
                      },
                    },
                  ],
            }
        };

    }

    mostrarTourInicio() {

        this.shepherdService.addSteps([
            {
                attachTo: {
                    element: '.step100',
                    on: 'bottom'
                },
                title: 'Cambiar Foto',
                text: ['Puede cambiar la foto que aparecerá en el programa de empresa y la aplicación quiosco.'],
                buttons: this.buttons,
            },
        ]);

        this.shepherdService.start();

    }


    mostrarTourPerfil() {

        this.shepherdService.complete();

        this.shepherdService.addSteps([
            {
                attachTo: {
                    element: '.step100',
                    on: 'bottom'
                },
                title: 'Cambiar Foto',
                text: ['Puede cambiar la foto que aparecerá en el programa de empresa y la aplicación quiosco.'],
                buttons: this.buttons,
            }

        ]);

        this.shepherdService.start();

    }

}

```

If I call to mostrarTourInicio, creates the tour and works well.  

If I call to the mostrarTourPerfil, creates the tour and works well.

But If I call mostrarTourInicio, and then mostrarTourPerfil or vice versa, the second one, shows a empty tour (all screen is locked and the arrows in the top left corner)

**Comment by jotae1e** [comment]
And, sorry for my insistence:

this.shepherdService.tourObject.steps <--- NOT EXIST

**Comment by jotae1e** [comment]
Sorry about your loosed time.  It was my mistake.  I used the same "classname" for the elements in different ionic page.  I supposed that when a page is destroyed, the components in the DOM are destroyed.  And then with the new page, the components are created.  

As you can see, in my example, the components are the same "classname".

I changed the "classname"  of the elements and works well.  Nice.

Thanks for your efforts.

And remember, this.shepherdService.tourObject.steps not exists, and may be exposed to access to a array of the steps.  Thanks a lot.
