### ISSUE TITLE
DIV shepherd-content empty after upgrade to Angular 9

### ISSUE THREAD

**Issue by harleybl** [shipshapecode/angular-shepherd#266]
I am in the process of upgrading an application to Angular 9.
In the application, we are using angular-shepherd a lot and it has been great.
Now that we are on angular 9 and have updated a lot of dependencies, the tour starts without errors, but the div that usually holds the content of the step is empty. This poses a problem since when the tour is set to modal, the whole page is locked. 

Here is my angular version info:
Angular CLI: 9.1.6
Node: 12.4.0
OS: darwin x64

Angular: 9.1.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.6
@angular-devkit/build-angular     0.901.6
@angular-devkit/build-optimizer   0.901.6
@angular-devkit/build-webpack     0.901.6
@angular-devkit/core              9.1.6
@angular-devkit/schematics        9.1.6
@angular/cdk                      9.2.4
@angular/cli                      9.1.6
@angular/material                 9.2.4
@ngtools/webpack                  9.1.6
@schematics/angular               9.1.6
@schematics/update                0.901.6
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

I am including angular-shepherd 0.6.0 and shepherd.js 7.1.5 in my package.json.

I will try to reproduce using the test project, but I am wondering if anyone has any ideas of why this might be happening. 

Thanks,
HB

**Comment by harleybl** [comment]
Actually I figured it out.

The shape of the step object changed from the old version I was using to 0.6.0.
The old shape was:
``` 
const step = {
    id: 'XXXXX',
    options: {
          attachTo: { .... }
          buttons: buttons
    ...
   } 
};
```

The new way does not have the "options" member, and the options are directly on the step now.

**Comment by rwwagner90** [comment]
Glad you figured it out @harleybl and sorry for the confusion!

**Comment by harleybl** [comment]
> Glad you figured it out @harleybl and sorry for the confusion!

No problem. The tour shows up now, but the positioning is off compared to the old version. Are there newer properties that I have to set now that have changed between 0.0.5 and 0.6.0?

**Comment by rwwagner90** [comment]
@harleybl options could have changed, yes. The step options are pretty well defined in Shepherd itself, so we could probably import the types and use that instead of `any`. We would definitely love a PR if you would like to take that on!
