### ISSUE TITLE
useModalOverlay does not work on defaultStepOptions

### ISSUE THREAD

**Issue by dimlucas** [shipshapecode/angular-shepherd#300]
When creating a new tour, the expected behavior is to set the `useModalOverlay` flag to true in `defaultStepOptions` and have the `shepherd-modal-overlay-container` svg element that is present in the DOM does not get the `shepherd-modal-is-visible` that is necessary to make it appear.

Digging into shepherd.js code, I found that the `useModalOverlay` setting is part of an options object passed in the `tourObject` but it's not present in angular-shepherd's typings. 

Using this:
`//@ts-ignore
this._service.tourObject.options.useModalOverlay = true;`

seems to be working for now. ts-ignore is needed to avoid compiler errors.

**Comment by rwwagner90** [comment]
@dimlucas that is correct, it's a tour option, not a step option. It is in the tour types https://github.com/shipshapecode/shepherd/blob/master/src/types/tour.d.ts#L144

**Comment by rwwagner90** [comment]
As per the examples in the README here, you use `this.shepherdService.modal = true;` to set modal in the angular service.
