### ISSUE TITLE
Angular 8.2.14 

### ISSUE THREAD

**Issue by FedericoEcheverria** [shipshapecode/angular-shepherd#353]
Hi, i use the exmaple https://github.com/shipshapecode/angular-shepherd but my error apears, when this line is added:
constructor(
		private shepherdService: ShepherdService
	) { }
Error: 
AppComponent_Host.ngfactory.js? [sm]:1 ERROR NullInjectorError: StaticInjectorError(AppModule)[AppComponent -> ShepherdService]: 
  StaticInjectorError(Platform: core)[AppComponent -> ShepherdService]: 
    NullInjectorError: No provider for ShepherdService!

Please help!

**Comment by rwwagner90** [comment]
@FedericoEcheverria what version of angular-shepherd are you using? To use Angular 8, you must use 0.5.0

**Comment by muhammedMoussa** [comment]
works fine with me

```
"@angular/core": "~10.0.3",
"angular-shepherd": "^0.7.0",
"shepherd.js": "^8.0.2",
```

**Comment by rwwagner90** [comment]
@muhammedMoussa right, but you are on Angular 10. The versions compatibility is listed in the README, so closing this.
