### ISSUE TITLE
Execute action from service

### ISSUE THREAD

**Issue by certifirm** [shipshapecode/angular-shepherd#428]
Is possible to execute an action, like a "click" in a button from the service.  

How can I do that.

Thanks

**Comment by rwwagner90** [comment]
@certifirm can you please explain what you mean?

**Comment by certifirm** [comment]
I wanted to simulate a "click" on a button from the service, change visibility layers, etc to interact with the page viewing the tour.   I have done it using observables. Thank you anyway.

**Comment by rwwagner90** [comment]
@certifirm I still don't understand what you mean. Clicking buttons outside of Shepherd? You want to interact with something on the page when a step shows or something? With more details I would be happy to provide some recommendations.
