### ISSUE TITLE
Steps array empty

### ISSUE THREAD

**Issue by certifirm** [shipshapecode/angular-shepherd#429]
If add steps with "addStep" method and then I access to the service steps array, always is empty.

```
this.shepherdService.addSteps(stepsLogin); // stepsLogin is an array with the steps.

console.log(this.shepherdService.steps) 
```
Is this the normal behaviour?

**Comment by rwwagner90** [comment]
Yes, the steps are not added to the Angular service, just to Shepherd itself https://github.com/shipshapecode/angular-shepherd/blob/master/projects/shepherd/src/lib/shepherd.service.ts#L115

You can do `this.shepherdService.tourObject.steps` I think.
