### ISSUE TITLE
`keyboardNavigation` option in tour instance is not available

### ISSUE THREAD

**Issue by NevenLiang** [shipshapecode/angular-shepherd#457]
In `0.7.0`, tour option `keyboardNavigation` is not available.

In `0.6.0`, step button option `disabled` is not available, but it works in `0.7.0`.

---

```
Compatibility

Angular 8: 0.5.0
Angular 9: 0.6.0
Angular 10: 0.7.0
```

About the compatibility in README, I think the code should be updated to work with latest Shepherd. Otherwise, user doesn't know which API is available in old version. Especially the Shepherd document is latest.

Even after updating the code to work with latest Shepherd, just keep the same minor version number, like this:

```
0.5.0 -> 0.5.1
0.6.0 -> 0.6.1
0.7.0 -> 0.7.1
```

Thanks!

**Comment by rwwagner90** [comment]
@NevenLiang we're not planning to update old versions. We mainly only support latest Angular and latest Shepherd in each new version.

**Comment by NevenLiang** [comment]
OK, I see. 

Shepherd is a great tools for guide tour. If the latest angular-shepherd supports the latest Shepherd is better.

**Comment by rwwagner90** [comment]
Everything should be up to date in the latest version
