### ISSUE TITLE
Realign major version number of package with Angular Core

### ISSUE THREAD

**Issue by bmcminn** [shipshapecode/angular-shepherd#472]
A lot of Angular libraries have started aligning their major versioning with Angular Core, so it is easier for people to know that v7.x, v8.x, v9.x, v10.x, etc is compatible with whichever version of Angular core they may be running.

It would simplify documenting and integrating this package a lot, since I have an app at work on Angular 6 and haven't been given the time to update it to Angular 10 yet, but my PM wants to see a demo of this module in our app this week and I can't tell if angular-shepherd 1, 2, 3, or 4 will do the trick for now...

**Comment by rwwagner90** [comment]
Hi @bmcminn that's a good suggestion 👍. I just looked back to the inception of this repo, and it seems to have started on Angular 7, so not sure any versions are compatible with Angular 6, I am afraid. https://github.com/shipshapecode/angular-shepherd/blob/b91ffbbf0244f61d08d8953a72a0181bbe36389f/package.json

**Comment by bmcminn** [comment]
Yeah, for now I'm leveraging Shepherd.js proper until I can get a dev budget for upgrading to Angular v10, but I'm def keeping this library in mind for when we get to that point :)

Keep up the great work :)

**Comment by rwwagner90** [comment]
Thanks @bmcminn! I'm not an Angular dev myself, so any suggestions you have here, I am happy to look into. Would love some help!

**Comment by rwwagner90** [comment]
This is done, thanks for the tip!
