### ISSUE TITLE
onTourFinish event doesn't fire

### ISSUE THREAD

**Issue by mruknowme** [shipshapecode/angular-shepherd#476]
```ts
this.shepherdService.onTourFinish = event => {
    console.log(event);
  }
```
`console.log` is never executed

**Comment by rwwagner90** [comment]
@mruknowme I'm not sure what you're trying to do is intended to work, and I don't think we documented that this should work?

If you want to execute code when the tour completes, try:

```js
this.shepherdService.tourObject.on('complete', (event) => {
  console.log(event);
});
```

**Comment by mruknowme** [comment]
Thanks for quick response @rwwagner90. I noticed this was not in documentation but intellisense suggested this option and it is in `shepherd.service.d.ts` file: 
```ts
     /**
     * This function is called when a tour is completed or cancelled to initiate cleanup.
     * @param completeOrCancel 'complete' or 'cancel'
     */
    onTourFinish(completeOrCancel: string): void;
```

Maye type reference is outdated? Anyways, what you suggested worked for me, thank you!

**Comment by rwwagner90** [comment]
@mruknowme ah, `onTourFinish` I believe is an internal method, not meant to be overridden, but I am not entirely sure.
