### ISSUE TITLE
Multiple tours?

### ISSUE THREAD

**Issue by KeithGillette** [shipshapecode/angular-shepherd#511]
From [the Shepherd.JS documentation](https://shepherdjs.dev/docs/tutorial-02-usage.html), I see that the underlying library supports the creation of an arbitrary number of tours. However, `angular-shephard` appears to wrap Shepherd in a single `providedIn: root` `ShepherdService`, which as a singleton, will only support a single application tour.

If one wishes to have multiple tours in a single Angular application, is subclassing `ShepherdService` with a custom service per tour the recommend approach?

**Comment by rwwagner90** [comment]
@KeithGillette can you explain your use case more? Are you trying to have two tours running at one time or are you wanting to create multiple tours just to have different sets of steps? If it's the latter I would recommend just using one tour and replacing the steps as needed.

**Comment by KeithGillette** [comment]
Thanks for your fast follow-up, @rwwagner90. I’m considering a couple of different use cases:

1. We have users with different roles to whom we’d want to present different onboarding content. 

2. We have application functionality we want to cover later than onboarding, triggered when the user has the need to know it.

I was anticipating implementing each of those cases as separate tours, each with its own set of steps.

I take it you’re recommending injecting ShepherdService into the components that would trigger any of those tours and having each of component reconfigure ShepherdSevice with the appropriate steps? 

I was thinking the better separation of concerns would be to encapsulate each tour to keep all setup logic out of components and only have the components trigger the injected tour based on user interaction.

**Comment by rwwagner90** [comment]
@KeithGillette I'm saying to create sets of steps for each use case, instead of trying to create a new tour for each case. Then use the steps based on roles or whatever you need:

```js
if (userHasRole) {
  this.shepherdService.addSteps(roleSpecificSteps);
} else {
  this.shepherdService.addSteps(defaultSteps);
}
```

**Comment by KeithGillette** [comment]
@rwwagner90, I can see that conditionally adding steps covers my first use case, since the user's role is exclusive. However, what about the second use case of triggering a tour of different application functionality separate from the main onboarding tour? If I'm reading the API correctly, `addSteps` is non-destructive, so if I were to use a single instance of `ShepherdService`, I'd have to call `removeStep` on every step in the main onboarding tour to clear that tour before again calling `addSteps` to build the follow-on tour. That's why I was thinking of subclassing `ShepherdService` in a separate Angular service for each tour, each with its own Shepherd tour.

**Comment by rwwagner90** [comment]
@KeithGillette so `addSteps` is actually destructive here. It calls `_initialize` which creates a new tour https://github.com/shipshapecode/angular-shepherd/blob/master/projects/shepherd/src/lib/shepherd.service.ts#L89

That may or may not be the best way to handle it, but I think for all of your cases creating sets of steps you add with `addSteps` will work.

We should likely expose a `destroy` method for tours to allow cleanup and better support this.

**Comment by KeithGillette** [comment]
Thanks, @rwwagner90. That makes sense now. Since the `angular-shepherd` documentation README just references the Shepherd.js documentation, I assumed the methods with the same name worked the same, but I see the `ShepherdService` wrapper method differs here. As you say, it may not be the best way to handle my use cases, but since it re-initializes the tour, just using `addSteps` would definitely cover them.

I still think it would be a better separation of concerns to handle tour setup configuration separately from tour initiation and control, so consider that a recommendation related to [the call for suggestions in the Usage NOTE in the README](https://github.com/shipshapecode/angular-shepherd#usage). I think [Apollo Angular's Query, Mutation, & Subscription services](https://apollo-angular.com/docs/data/services) provide a good example in this respect. In the Apollo Angular case, one creates a service subclassing the `apollo-angular` Query, Mutation, or Subscription service and assigns the Query, Mutation, or Subscription to a class property. To execute the Query, Mutation, or Subscription, one injects the derived service into a component or another service and calls the parent class methods. Likewise, I could see assigning tour steps to a property on a service subclassing `ShepherdService`, and then injecting that derived service to start and control the tour.

**Comment by rwwagner90** [comment]
@KeithGillette I'm not an Angular dev, but if you were interested in contributing this to the library, PRs are welcome!
