### ISSUE TITLE
Add `type` to interface `StepOptionsButton`

### ISSUE THREAD

**Issue by CherniyFY** [shipshapecode/angular-shepherd#559]
If I try to add `type` to button using `tourObject.getById().updateStepOptions()` I get the following error:

> Type '{ classes: string; text: string; type: string; }' is not assignable to type 'StepOptionsButton'.
  Object literal may only specify known properties, and 'type' does not exist in type 'StepOptionsButton'.ts(2322)

This happens because interface `StepOptionsButton` doesn't have `type`, in comparison we can set `type` on button in `addSteps()` because its param is `Array<any>`.

**Comment by rwwagner90** [comment]
@CherniyFY sorry for the confusion! `type` is not a valid thing on a Shepherd button. We added it to this angular wrapper, for ease of making buttons with a specific type. You can see the built in types here https://github.com/shipshapecode/angular-shepherd/blob/master/projects/shepherd/src/lib/utils/buttons.ts#L11

So this error you are seeing is correct. Honestly, we should probably remove this convenience method and just use the normal Shepherd API.

**Comment by CherniyFY** [comment]
In that case, also should probably remove it from readme

**Comment by rwwagner90** [comment]
@CherniyFY it does currently exist in this wrapper, I am saying it's not a Shepherd thing, it's an angular-shepherd thing, so the type hierarchy you are looking for does not exist.
