### ISSUE TITLE
Error Typescript 2709  Cannot use namespace 'Shepherd' as a type.`

### ISSUE THREAD

**Issue by matte00** [shipshapecode/angular-shepherd#6]
Hi mate,

i trying your create angular library but when try to compile with typescript 2,9,2 i riceved this error:

`ERROR in node_modules/angular-shepherd/lib/shepherd.service.d.ts(15,17): error TS2709: Cannot use namespace 'Shepherd' as a type.`

Any idea?

**Comment by rwwagner90** [comment]
Can you give me some more info please? What angular version, how do you have angular-shepherd installed, etc? I do not have much Angular experience, but I would definitely like to make sure this works.

**Comment by matte00** [comment]
Hi @rwwagner90 adnd thank you for you response.
I'm using angular 5.2.11 in my current project and i can't upgrade it at the moment. 
I have installed 

- angular-shepherd 0.0.4 by `npm install angular-shepherd --save` 

- shepherd.js 2.8.0 by `npm install shepherd.js --save` 

- typescript versione 2.9.2

- webpack 3.12.0

- node v10.13.0

- npm 6.4.1

Thank you alot for your help. Have a nice day!

**Comment by rwwagner90** [comment]
@matte00 This was written with Angular 7, and likely only works with Angular 7+, so unfortunately, it may not work for you. I would be glad to support other versions, if you and/or others wanted to help me figure out how to do so. I think things are breaking every time there is a major update and there is not a way to support more than one Angular version.

**Comment by tomvangreen** [comment]
> @matte00 This was written with Angular 7, and likely only works with Angular 7+, so unfortunately, it may not work for you. 

@matte00 
Yeah, this is most likely the problem. Though this library is just a thin wrapper over shepherd. You should be able to clone this repository and then copy the content of the lib folder into your source code ( https://github.com/shipshapecode/angular-shepherd/tree/master/projects/shepherd/src/lib ). You still need to install shepherd manually with npm, but I think the services provided by this library should still work with angular 5. 

It's not the best solution as you would have to make sure you update the source manually, but at least you should be able to use angular-shepherd like that.

**Comment by matte00** [comment]
thank you @rwwagner90 @tomvangreen i'll try it!
