### ISSUE TITLE
Not Compatible with angular 12

### ISSUE THREAD

**Issue by swapnilingle15** [shipshapecode/angular-shepherd#687]
Getting below error 

 npm ERR! code ERESOLVE
06:00:08   npm ERR! ERESOLVE unable to resolve dependency tree
06:00:08   npm ERR!
06:00:08   npm ERR! While resolving: portal@0.0.0
06:00:08   npm ERR! Found: **@angular/common@12.0.5**
06:00:08   npm ERR! node_modules/@angular/common
06:00:08   npm ERR!   **@angular/common@"~12.0.0"** from the root project
06:00:08   npm ERR!
06:00:08   npm ERR! Could not resolve dependency:
06:00:08   npm ERR! peer **@angular/common@"^11.0.0" from angular-shepherd@11.0.0**
06:00:08   npm ERR! node_modules/angular-shepherd
06:00:08   npm ERR!   angular-shepherd@"^11.0.0" from the root project
06:00:08   npm ERR!
06:00:08   npm ERR! Fix the upstream dependency conflict, or retry
06:00:08   npm ERR! this command with --force, or --legacy-peer-deps
06:00:08   npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
06:00:08   npm ERR!
06:00:08   npm ERR! See /root/.npm/eresolve-report.txt for a full report.

**Comment by pelord** [comment]
Same issue!

**Comment by sepatel** [comment]
PR #688  fixes this up but nobody seems to be active enough to actually do anything with it. Unsure how to get a persons attention to this matter.

**Comment by pelord** [comment]
I will try your branch !

**Comment by pelord** [comment]
@shipshapecode Any plan to publish the angular 12 version on NPM?

**Comment by rwwagner90** [comment]
@pelord I just published 12.0.0. Can you please give it a try?

**Comment by pelord** [comment]
yep! thanks!

**Comment by rwwagner90** [comment]
Please let me know if it works for you and we can close this issue

**Comment by rwwagner90** [comment]
@pelord did it work?

**Comment by pelord** [comment]
@rwwagner90 I will test it today!

**Comment by pelord** [comment]
@rwwagner90 I have some issues building my app with others dependencies.. I will continue tomorrow! sorry! Still in progress !

**Comment by pelord** [comment]
It's working properly. The issue could be closed.
