### ISSUE TITLE
No CSS files in the /dist folder, problems with theme customization in Angular

### ISSUE THREAD

**Issue by luizdanielmlima** [shipshapecode/angular-shepherd#69]
(sorry, I posted this in the Abraham project)

Hello @jabbett ,

Thank you for your support. I´m using Angular Shepherd in my project. Since the themes (css files) are not included in the dist folder, I´m REALLY having a hard time changing it´s colors, etc.

Since I didn´t want to include any CSS in the node_modules/shepherd.js, I tried to customize it through a shepherd-theme.scss file, placed in the /src folder of my angular project and @import it in the styles.scss. But doing things like this:

.shepherd { &-header { background: purple; } &-button { border: 1px solid red; } }
is not working....

Any help would be very much appreciated! Thank you

**Comment by rwwagner90** [comment]
@luizdanielmlima we need to update this wrapper to Shepherd v6, then it should be easier to customize the styles.

**Comment by jabbett** [comment]
No worries @luizdanielmlima - I basically posted what @rwwagner90 said ;)

**Comment by luizdanielmlima** [comment]
Thank you guys, my version is 5.0.1 so I will upgrade as soon as I can. In the end I managed to customize it by putting a **!important** in everything. I believe it´s because Shepherd´s CSS has a high specificity. Thank you again for your help!

**Comment by luizdanielmlima** [comment]
Well, I just re-installed angular-shepherd, but it seems that is still uses shepherd.js 5.0.1, so I will wait when you release an update on angular-shepherd ;-)

**Comment by rwwagner90** [comment]
@luizdanielmlima yeah, we have no updated to v6 here yet, but will soon.

**Comment by rwwagner90** [comment]
@luizdanielmlima I have updated to v6 now, and released angular-shepherd 0.4.0.

**Comment by luizdanielmlima** [comment]
Thank you!
