### ISSUE TITLE
IE support?

### ISSUE THREAD

**Issue by mruknowme** [shipshapecode/angular-shepherd#7]
Doesn't work in IE because shperd.js 2.5.0 uses class syntax. Is it possible to add support from the package side?

Any suggested solutions?

Thanks

**Comment by rwwagner90** [comment]
We recently dropped IE support in Shepherd, but we are planning to add it back soon. Follow https://github.com/shipshapecode/shepherd/issues/351 for more info

**Comment by rwwagner90** [comment]
We just released angular-shepherd 0.0.5, it should support IE again!
