### ISSUE TITLE
How to Create Custom Theme?

### ISSUE THREAD

**Issue by Ryllau** [shipshapecode/angular-shepherd#79]
Currently, I am trying to create custom styling to my first step but it seems like my styling is not taking precedence over the default styling.

`this.shepherdService.addSteps([{
            id: 'test',
            classes: 'shepherd',
            buttons: [
                {
                    text: 'Next',
                    type: 'next'
                }
            ],
            text: 'Hello!',
            attachTo: {
                element: '.header-app-icon',
                on: 'right'
            },
        }]);`

`.shepherd{
border-width: 2px !important; 
border-style: solid !important;
background-color: red !important;
}`

The documentation is not clear to me how to go about this. Any help?

**Comment by rwwagner90** [comment]
@Ryllau I would have to see an example to determine why those styles are not working. We override a lot of styles for the landing page, if you want to reference that. https://github.com/shipshapecode/shepherd/blob/master/landing/css/styles.css#L107-L237

**Comment by Ryllau** [comment]
![Screen Shot 2019-11-14 at 1 21 02 PM](https://user-images.githubusercontent.com/36181960/68884685-a8587880-06e1-11ea-9df7-575edb9e7d76.png)

This is what I am currently seeing. I would like to style this to look a little more appealing by adding a border and changing the background color.

**Comment by rwwagner90** [comment]
@Ryllau a screenshot doesn't help me to help you. I provided the styles where we overrode everything for the demo site. That should be very helpful for what you are trying to do. Is there something I can help you understand?

**Comment by Ryllau** [comment]
hmmm. Yeah I am confused. I thought the classes: attribute within the addSteps function allows you to add your own custom css styles. However, when I create something like this... 
buttons: [
                {
                    classes: 'my-custom-css',
                    text: 'Next',
                    type: 'next'
                }
            ],

my css does not take precedence.

**Comment by rwwagner90** [comment]
@Ryllau you have to look at the specificity. CSS does not work like that. Have you taken a look at this? https://github.com/shipshapecode/shepherd/blob/master/landing/css/styles.css#L107-L237

Adding a class simply adds a class. Normal CSS rules still apply. So if you have like `my-class` you cannot expect this to do anything:

```css
.my-class {
  background: blue;
}
```

You would instead want to do something like:

```css
.my-class.shepherd-element {
  background: blue;
}
```

Again, I cannot really help you without seeing the code, but do you understand what I mean here?

**Comment by Ryllau** [comment]
right! you are correct. Sorry, I am still learning. I appreciate your help and being patient with me for something basic!
