### ISSUE TITLE
add shepherd types

### ISSUE THREAD

**Issue by behroozbc** [shipshapecode/angular-shepherd#793]
hi 
I see [this types](https://github.com/shipshapecode/shepherd/blob/master/src/types/step.d.ts) but in service methods like [addsteps](https://github.com/shipshapecode/angular-shepherd/blob/3a62edbf59826cebf50bcfc5fb347bbb0a657522/projects/shepherd/src/lib/shepherd.service.ts#L88) is any[], in typescript prefer have type .
I want to know why use any ?
and can I add type for some method ?

**Comment by rwwagner90** [comment]
@behroozbc feel free to fix the types!
