### ISSUE TITLE
zone.js dependency is outdated

### ISSUE THREAD

**Issue by NewSnowflake** [shipshapecode/angular-shepherd#797]
> code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: xxxxxxx
> npm ERR! Found: zone.js@0.11.4
> npm ERR! node_modules/zone.js
> npm ERR!   zone.js@"^0.11.3" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer zone.js@"~0.10.3" from @angular/core@10.2.5
> npm ERR! node_modules/@angular/core
> npm ERR!   @angular/core@"^10.2.3" from the root project
> npm ERR!   peer @angular/core@"10.2.5" from @angular/common@10.2.5
> npm ERR!   node_modules/@angular/common
> npm ERR!     @angular/common@"^10.2.3" from the root project

Would it be possible to update the angular-shepherd zone.js dependency to 0.11.x without issues?

**Comment by rwwagner90** [comment]
@NewSnowflake please feel free to open a PR!
