### ISSUE TITLE
support angular 13

### ISSUE THREAD

**Issue by behroozbc** [shipshapecode/angular-shepherd#847]
hi 
angular 13 release last week 
any plane to support it ?

**Comment by rwwagner90** [comment]
@behroozbc of course. Would you like to open a PR adding support?

**Comment by behroozbc** [comment]
@rwwagner90 sounds good I do it.
one thing I install node 16 and generate package lock json version 2 Its okay

**Comment by behroozbc** [comment]
@rwwagner90 
hi when new version publish to npm ?

**Comment by rwwagner90** [comment]
@behroozbc it should be published now
