### ISSUE TITLE
navigate like routing

### ISSUE THREAD

**Issue by kishorekumarvajravel** [shipshapecode/angular-shepherd#852]
Hi,

There is any way to route a page using the router link or any other way ??

Like => this.router.navigateByUrl(['/redirecturl']);

Not using location.href="redirectUrl";

please update and thanks,

**Comment by rwwagner90** [comment]
@kishorekumarvajravel you can change pages however you see fit. I would hide the tour before transitioning and then show it again once you are fully transitioned. You may need to leverage `beforeShowPromise` for this.

**Comment by yc-98** [comment]
Hii @rwwagner90 ,
I tried this.router.navigateByUrl(['/redirecturl']); . But doesn't work that way.
message in browser console-
ERROR TypeError: Cannot read properties of undefined ( reading 'navigateByUrl')
console.log works but this doesn't which make me think if while executing shepherd service is not able to refer to navigateByUrl ( I did import this in the component where i use the tour but still the problem persists).

**Comment by rwwagner90** [comment]
@yc-98 sounds like you are not binding your scope right and `this.router` is undefined.

**Comment by verygreenboi** [comment]
> 

You'll need to bind the function to the component scope.
