### ISSUE TITLE
wrong dependency in version 13

### ISSUE THREAD

**Issue by jorisbaiutti** [shipshapecode/angular-shepherd#896]
When installing on angular 13 project => dependency error because it references "@angular/common": "^12.2.1"
should be "@angular/common": "^13.1.0"

https://github.com/shipshapecode/angular-shepherd/blob/c4af6ef6fd23d4c6233833007bca7ed669323458/projects/shepherd/package.json#L22

**Comment by rwwagner90** [comment]
Should be fixed
