### ISSUE TITLE
Anybody working on Angular-Dart wrapper?

### ISSUE THREAD

**Issue by ayushin** [shipshapecode/angular-shepherd#9]
Hi,

Looks like a really great intro/tour package, we'd love to use it with our Angular/Dart application https://portal.aahi.io - has anyone looked at making an angular-dart wrapper?

Regards,

Alex

**Comment by rwwagner90** [comment]
@ayushin I barely was able to throw together this angular one. I am not familiar with dart, but would definitely be open to supporting it. Would you be able to help us throw something together?

**Comment by ayushin** [comment]
Yes, I guess I could, but I am very very short on time at this moment. Basically the way forward would be to look at the implementation of I guess google_maps https://pub.dev/packages/google_maps which interfaces with google maps javascript library and does similar to what we want, but our challenge is way simpler than that :) if you have the time/resources than i certainly would be very willing to advice

**Comment by rwwagner90** [comment]
I think having some blog posts or guides on how to do it or some sort of starting point, would be good.
